### ISSUE TITLE
[BUG]: Optional parameters are forced

### ISSUE THREAD

**Issue by KillerJulian** [ClementNerma/tapo-rest#18]
Hello,  
before I started using this bridge, I tried the Python interface. I used the same endpoint and did not need to specify an `end_date`. It still worked.

**Request:**
```
http://localhost:8000/actions/p110/get-hourly-energy-data?device=<device_name>&start_date=%2B2024-12-01
```

**Response:**
```
400 Failed to deserialize query string: missing field `end_date`
```

I'm not sure if `start_date could` also be an optional parameter. Also, can you please explain more about the RFC3339 format? On the internet I found several ways to specify the format, like `2024-12-01T09:00`, but not everything worked with your API (`Failed to deserialize query string: trailing input`).

**Comment by ClementNerma** [comment]
The way the Python library works is that it actually only considers the date you're providing. You cannot specify an hour, minute or second as it will be omitted entirely.

The end date, when not specified, falls back to the start date, but only in the Python library ; the original Rust library doesn't do that. I've adjusted this behaviour in the latest commit so now you should be able to omit the `end_date` parameter entirely. The docker image takes a while to build so it should only be live in ~1 hour.

RFC3399 requires dates to be written just like you did: `+2024-12-01` for instance (note that you can omit the `+` sign if you want). No method currently supports timestamps, in order to avoid confusion with the fact they're going to be emitted anyway.

Let me know if you have other issues!

**Comment by KillerJulian** [comment]
@ClementNerma I
 have just tested it. Furthermore, the specification of the `end_date` is still required

**Comment by KillerJulian** [comment]
Rust and alphine provide their images directly under the name `linux/arm64/v8`.

**Comment by ClementNerma** [comment]
This is weird, did you test with the latest release/docker image? I can't reproduce this problem locally...

**Comment by KillerJulian** [comment]
Tried out with the latest Docker image for amd/64

**Comment by ClementNerma** [comment]
I've cleaned up the Docker images. Can you pull the latest tag again and run the container with only the `-V` flag please? Like this:

```shell
docker pull clementnerma/tapo-rest:latest
docker run -it --rm clementnerma/tapo-rest:latest -V
```

And ensure that the output is `tapo-rest 0.2.4`
