### ISSUE TITLE
`Exited with code 0` on container image `arm/64`

### ISSUE THREAD

**Issue by KillerJulian** [ClementNerma/tapo-rest#20]
Unfortunately I cannot start the image. When I try to do this, the Comtainer is stopped immediately. It could also be due to a misconfiguration on my part:

```bash
pi@xyz:/srv/my-project$ sudo docker compose up
[+] Running 1/0
 ✔ Container Tapo-REST-Bridge  Created                                                                           0.0s 
Attaching to Tapo-REST-Bridge
Tapo-REST-Bridge exited with code 0
```

```compose
name: My project

services:
  tapo-rest:
    container_name: Tapo-REST-Bridge
    image: docker.io/clementnerma/tapo-rest:latest
    platform: linux/arm64
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ./data/devices.json:/app/devices.json:ro
    environment:
      - TAPO_EMAIL=${TAPO_EMAIL}
      - TAPO_PASSWORD=${TAPO_PASSWORD}
      - AUTH_PASSWORD=${TAPO_REST_AUTH_PASSWORD}
      - PORT=8080
    ports:
      - 8080:8080
```

**Comment by KillerJulian** [comment]
Could the reason be that the Pi expects `linux/arm64/v8`, but I only pass `linux/arm64`? Normally these should be compatible with each other. Maybe dependencies are missing?

**Comment by KillerJulian** [comment]
Rust and alphine provide their images directly under the name `linux/arm64/v8`.

**Comment by ClementNerma** [comment]
This is not a platform problem, otherwise you would get the following message:

```
Tapo-REST-Bridge  | exec ./tapo-rest: exec format error
```

I don't know why this problem happens though, I don't have an RPi to test but on an x64 machine your compose file (with the `platform` field changed to `linux/amd64`) works fine...

**Comment by ClementNerma** [comment]
Can you pull the latest image and try again? This should normally solve your problem (no idea what it was but I just improved docker images build so maybe it works for you know)

**Comment by KillerJulian** [comment]
At least log issues now...

```
pi@my:/project$ docker compose up
Attaching to Tapo-REST-Bridge
Tapo-REST-Bridge exited with code 0
Tapo-REST-Bridge exited with code 159
Tapo-REST-Bridge exited with code 159
Tapo-REST-Bridge exited with code 159
Tapo-REST-Bridge exited with code 159
Tapo-REST-Bridge exited with code 159
Tapo-REST-Bridge exited with code 159
Tapo-REST-Bridge exited with code 159
```

I suspect that the wrong architecture or the wrong binaries are now being used

**Comment by ClementNerma** [comment]
This is weird, I'm only publishing an `amd64` and an `arm64` (v8) image. I don't know why it's pulling something else.

I won't provide `arm32v7` images as these aren't supported as [tier 1](https://doc.rust-lang.org/nightly/rustc/platform-support.html) by the Rust infra, which means they may not work properly and cause various kind of issues that I'm not honestly not too keen on debugging.

Given you `uname -m` command returns an `aarch64` indicator, it should work with an `arm64` image ; I don't get why it's not working. On my computer, the arm64 version runs fine:

```shell
# Requires to have QEmu installed and registered in Docker
docker run --platform=linux/arm64/v8 --rm -t clementnerma/tapo-rest
```

So let's try it another way ; could you please clone the repository and built it locally? e.g.:

```shell
git clone https://github.com/ClementNerma/tapo-rest
cd tapo-rest
cargo build -r
mkdir -p target/building-for-docker/artifacts/linux/arm64
cp target/release/tapo-rest target/building-for-docker/artifacts/linux/arm64/tapo-rest
docker build -t tapo-rest .
docker run --rm -t tapo-rest
```

This should normally work. If it doesn't, we can iterate from here to see exactly where the problem comes from.

**Comment by KillerJulian** [comment]
Please excuse my delayed answers, but I have to push another project at the moment. I am also trying to get a container with my software to run on the Pi. If this is successful I will try to get this project running as well. I will get back to you as soon as I have time again (probably at the end of January).

**Comment by KillerJulian** [comment]
### The problem

I have now set up another PI as a test environment to find out the error.

According to my research, the PI uses a 64-bit kernel, which causes the output of `uname`. However, no 64-bit applications can be started because the userspace is based on 32-bit, which in turn explains why Docker tries to obtain `linux/arm/v7` images.

Now it's time to think about how to get this project running on a 32-Bit PI. I guess this issue could affect more users.

### Search for a solution

If possible, upgrade to a 64-bit OS. That's the least painful way.

However, if this is not possible, as in my case, because a custom image must be used, we will have to find another way. Since I suspect that it could affect other users (e.g. Raspberry Pi 2), I would like to look for a possibility with you.

There are currently two possibilities for me:

- Deploy a multi-arch image for `arm32`
- Docker emulation with QEMU
- Possibly build a new userspace with 64 bit (not preferred)*

---

I will stay on the topic

**Comment by ClementNerma** [comment]
Hi, I ended up just building a new image with the `linux/arm/v7` target, which _should_ theorically work fine.
Given it's not a tier-1 platform on Rust I'm not sure it'll always work perfectly, but for the time being it should, at least.
Can you try it and tell if it works on your site?

**Comment by KillerJulian** [comment]
Thanks, man! 🤝

Why did you decide to build the Rust files outside of Docker and then move them into the container? I have no idea about Rust, but would building via Dockerfile specifying the platform with QEMU be sufficient?

I will check if the image works for `arm/v7`. I can also understand if it is too much work for you to support an `arm/v7` image

**Comment by ClementNerma** [comment]
Qemu has soooo many problems on my local setup, I couldn't for the life of me getting it to build programs properly for other architectures, so I just resorted to `cross` which is actually a program that allows you to compile cross-platform Rust binaries by using an underlying Docker or Podman interface.

So basically it takes are of all the configuration, problems handling etc. for me and I get a final binary. Plus I had already this setup for previous projects where I didn't need Docker images at all but still needed binaries for several different targets.

In the end using it to build the binaries and _then_ wrapping them into a Docker image was the simplest thing to do for me. Not the most proper but it was getting a bit too difficult otherwise.

**Comment by KillerJulian** [comment]
The image seems to work perfectly, I have not noticed any problems so far. If problems should come up, I will open this issue again

Many thanks you for your work 🎉
