### ISSUE TITLE
Please make reading of a password from file

### ISSUE THREAD

**Issue by smiklosovic** [ClementNerma/tapo-rest#9]
@ClementNerma 

Exposing that on a command line is visible e.g. when I wrote a systemd unit. Putting a password into a file and reading it from there is safer.

**Comment by ClementNerma** [comment]
Hi,

Would reading a password from an environment variable be an option for you?

**Comment by smiklosovic** [comment]
I am not sure, if systemd unit can handle that ...

**Comment by ClementNerma** [comment]
Hi,

Sorry the delay I haven't been able to make real updates to the project these past few weeks.

I've now added an option called `--password-from-file` (`-f`) that you can provide instead of `--auth-password`.

It's available in the new `0.1.2` version (you can find it in the releases tab: https://github.com/ClementNerma/tapo-rest/releases/tag/v0.1.2).

Have a nice day :)
